# -*- coding: utf-8 -*-
"""Scraping_Tokopedia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MD9UU0YnqzYvPlkHAjcW8GXIgjj4iSmW
"""

!pip install google-play-scraper

from google_play_scraper import app, reviews, Sort, reviews_all
import pandas as pd

from google_play_scraper import reviews, Sort

scrape_review, _ = reviews(
    'com.tokopedia.sellerapp',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=11000
)

import csv

with open('review_tokopedia_seller.csv', mode='w', newline='', encoding='utf-8') as file :
  writer = csv.writer(file)
  writer.writerow(['Review'])
  for review in scrape_review :
    writer.writerow([review['content']])

df = pd.DataFrame(scrape_review)
df.shape
df.head()
df.to_csv('review_tokopedia_seller.csv', index=False)

df = pd.DataFrame(scrape_review)

jumlah_review, jumlah_kolom = df.shape
print(f"Jumlah review: {jumlah_review}")
print(f"Jumlah kolom: {jumlah_kolom}")

df.head()

